### ISSUE TITLE
Identity customization:A key cannot be configured on 'ApplicationUserClaim' because it is a derived type.

### ISSUE THREAD

**Issue by The-DevOps-Guy** [dotnet/AspNetCore.Docs#12373]
[EDIT by guardrex ... content moved here from #12372]

# Step
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#add-all-navigation-properties

# Issue description

After following this and attempting to execute the web application, an error is raised at    `base.OnModelCreating(modelBuilder);`

> System.InvalidOperationException
  HResult=0x80131509
  Message=A key cannot be configured on 'ApplicationUserClaim' because it is a derived type. The key must be configured on the root type 'IdentityUserClaim<string>'. If you did not intend for 'IdentityUserClaim<string>' to be included in the model, ensure that it is not included in a DbSet property on your context, referenced in a configuration call to ModelBuilder, or referenced from a navigation property on a type that is included in the model.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.SetPrimaryKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.PrimaryKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasKey(Expression`1 keyExpression)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext`5.<>c.<OnModelCreating>b__20_1(EntityTypeBuilder`1 b)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext`5.OnModelCreating(ModelBuilder builder)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`8.OnModelCreating(ModelBuilder builder)
   at Identity.Data.IdentityDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\devuser\Source\Repos\Identity\Data\IdentityDbContext.cs:line 24

The class it is complaining about is exactly as defined in the documentation. Also all other classes as per docs. 

```csharp
public class ApplicationUserClaim : IdentityUserClaim<string>
{
      public virtual ApplicationUser User { get; set; }
}
```

# Software versions

- .NET Core 2.2 
- Microsoft.AspNetCore.Identity.EntityFrameworkCore 2.2.0
- Microsoft.EntityFrameworkCore.SqlServer 2.2.4
- Microsoft.EntityFrameworkCore.Tools 2.2.4

```
<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>
dotnet --info 
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
</details>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#add-all-navigation-properties)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by guardrex** [comment]
Hello @The-DevOps-Guy ... We just need one issue open for it. This is a little better for us to track because it has the topic metadata.

# Step
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#add-all-navigation-properties

# Issue description

After following this and attempting to execute the web application, an error is raised at    `base.OnModelCreating(modelBuilder);`

> System.InvalidOperationException
  HResult=0x80131509
  Message=A key cannot be configured on 'ApplicationUserClaim' because it is a derived type. The key must be configured on the root type 'IdentityUserClaim<string>'. If you did not intend for 'IdentityUserClaim<string>' to be included in the model, ensure that it is not included in a DbSet property on your context, referenced in a configuration call to ModelBuilder, or referenced from a navigation property on a type that is included in the model.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.SetPrimaryKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.PrimaryKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasKey(Expression`1 keyExpression)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext`5.<>c.<OnModelCreating>b__20_1(EntityTypeBuilder`1 b)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext`5.OnModelCreating(ModelBuilder builder)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`8.OnModelCreating(ModelBuilder builder)
   at Identity.Data.IdentityDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\devuser\Source\Repos\Identity\Data\IdentityDbContext.cs:line 24

The class it is complaining about is exactly as defined in the documentation. Also all other classes as per docs. 

>   public class ApplicationUserClaim : IdentityUserClaim<string>
    {
        public virtual ApplicationUser User { get; set; }
    }


# Software versions

- .NET Core 2.2 
- Microsoft.AspNetCore.Identity.EntityFrameworkCore 2.2.0
- Microsoft.EntityFrameworkCore.SqlServer 2.2.4
- Microsoft.EntityFrameworkCore.Tools 2.2.4

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>
dotnet --info 
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
</details>

**Comment by The-DevOps-Guy** [comment]
I cannot edit the above anymore, so note this correction to the text.

```
public class ApplicationUserClaim : IdentityUserClaim<string>
 {
       public virtual ApplicationUser User { get; set; }
 }
```

**Comment by guardrex** [comment]
oh ... no worries ... I'll update it.

**Comment by The-DevOps-Guy** [comment]
Hi, I have created a example project with this issue for you to reproduce. 
To see, all you need to do is run the following command in the Package Manager Window.
>Add-Migration Init -Context ApplicationDbContext

Solution: https://drive.google.com/file/d/1gXqpyamax-SQVU6F006AlCsc-mcZNRJZ/view?usp=sharing

**Comment by The-DevOps-Guy** [comment]
Not sure if this is related, but I noticed the Microsoft.AspNetCore.App 2.2.0 includes...

- Microsoft.AspNetCore.Identity.EntityFrameworkCore v2.2.0

Which in turn includes...

- Microsoft.EntityFrameworkCore.Relational 2.2.0

But the stand alone package Microsoft.AspNetCore.Identity.EntityFrameworkCore 2.2.0 includes...

- Microsoft.EntityFrameworkCore.Relational 2.2.4

Not sure why this is.

**Comment by The-DevOps-Guy** [comment]
Hi, thanks for looking at this. Just to say, I may not respond tomorrow until 17:00 GMT.

**Comment by The-DevOps-Guy** [comment]
Hi, I wonder if you could provide an ETA on when the product team may be able to take a look into this ?
Do you feel it would be worthwhile escalating via our MS enterprise agreement and our TAM?
It's good to help the community, but we could do with this looking into quite quickly.
Thanks for all your efforts.

**Comment by The-DevOps-Guy** [comment]
I hope this helps anyone else who finds this issue. I have fixed this. The issue was actually within the ApplicationUser class. While this might indicate the error raised is not reporting the underlying issue, the problem was the declarations for the navigation properties were typed with the **Identity**... rather than 
the **Application**... derived types. 

**Before**

`public virtual ICollection<IdentityUserClaim<string>> Claims { get; set; }`
`public virtual ICollection<IdentityUserLogin<string>> Logins { get; set; }`
`public virtual ICollection<IdentityUserToken<string>> Tokens { get; set; }`

**After (fixed)**

`public virtual ICollection<ApplicationUserClaim> Claims { get; set; }`
`public virtual ICollection<ApplicationUserLogin> Logins { get; set; }`
`public virtual ICollection<ApplicationUserToken> Tokens { get; set; }`

**Comment by The-DevOps-Guy** [comment]
That said, Add-Migration is creating a erroneous UserID1 field across all tables. 

i.e.
`                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetUsers_UserId1",
                        column: x => x.UserId1,
                        principalSchema: "asp_security",
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);`

**Comment by Soundman32** [comment]
I have almost the same problem, but in my case, the collections are correct.  Core 2.1, EF Core 2.1.1
>System.InvalidOperationException: A key cannot be configured on 'ApplicationUserRole' because it is a derived type. The key must be configured on the root type 'IdentityUserRole<string>'. If you did not intend for 'IdentityUserRole<string>' to be included in the model, ensure that it is not included in a DbSet property on your context, referenced in a configuration call to ModelBuilder, or referenced from a navigation property on a type that is included in the model.

**Comment by Soundman32** [comment]
Why is it, 5 minutes after posting 'it doesn't work', I get it working.   Turns out I didn't have the correct DbContext, specifically, I hadn't specified ApplicationUserRole:
>class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, string, IdentityUserClaim<string>, ApplicationUserRole, IdentityUserLogin<string>, IdentityRoleClaim<string>, IdentityUserToken<string>>

**Comment by guardrex** [comment]
The :pray: *server gods* :pray: play with us mere mortals!

**Comment by bdshanto** [comment]
Still this issues open in net5😒

**Comment by FariborzRazban** [comment]
same problem in dotnet 5 :(

**Comment by TechScribe-Deaf** [comment]
Still same problem on Dotnet 8.0.1. I may have to get rid of Entity Framework Core at this point if there is no viable resolution. Frustrating indeed.

**Comment by guardrex** [comment]
This one seems to have gotten itself good and ***stuck in the mud***.

I'm chatting with the product unit today, and I'll mention this to them. One side note on this one getting worked is that it was assigned (or there was an ***ASK*** ... "assigned" is probably too strong of a word) for Safia to take a look. However, she left this product unit a while ago, so she certainly won't be the one to look into it.

I'll be sure to raise this issue with the product unit today (2/9/2024) to see if someone can be assigned to it.

**Comment by guardrex** [comment]
I raised this on 2/9, but it fell through the cracks (again).

@TechScribe-Deaf ... I recommend that you open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

I think you can provide a thumbnail summary of the problem, cross-link to this issue, and put up a minimal repro project that minimally demonstrates the problem ... cross-link your GH repro project into the issue so that they can look at it (or run it locally).

After you've received feedback/guidance from them, I recommend that you come back and cross-link (or state) here what happened.

**Comment by abramjablonski** [comment]
@TechScribe-Deaf - the solutions from @Soundman32 and @The-DevOps-Guy seem to work, if you do them both (derive from the identity classes, and use the long constructor for ApplicationDbContext...  my code:

    public class ApplicationRole : IdentityRole<string> { }
    public class ApplicationUserRole : IdentityUserRole<string> { }
    public class ApplicationUserLogin : IdentityUserLogin<string> { }
    public class ApplicationRoleClaim : IdentityRoleClaim<string> { }
    public class ApplicationUserClaim : IdentityUserClaim<string> { }
    public class ApplicationUserToken : IdentityUserToken<string> { }


    public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, string, ApplicationUserClaim, ApplicationUserRole, ApplicationUserLogin, ApplicationRoleClaim, ApplicationUserToken>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }

**Comment by guardrex** [comment]
There's no further feedback on this issue from the community, and WRT to the section ...

> the problem was the declarations for the navigation properties were typed with the Identity... rather than
the Application... derived types.

... the section shows using `Application`-based types matching https://github.com/dotnet/AspNetCore.Docs/issues/12373#issuecomment-492997022 ...

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#add-all-navigation-properties

I don't see an actionable change to make, so we'll close this now and take further feedback if anyone is still having a problem.
