### ISSUE TITLE
NoClassDefinitionFound SignalR with Java client

### ISSUE THREAD

**Issue by shudson302** [dotnet/AspNetCore.Docs#13296]
version 1.0.0 of SignalR and java vesrion 12.0.1 of java. I am using the SignalRChat sample from the AspNetCore.Docs sample found here:

https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/signalr/java-client/sample

Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/signalr/HubConnectionBuilder
at Chat.main(Chat.java:16)
Caused by: java.lang.ClassNotFoundException: com.microsoft.signalr.HubConnectionBuilder
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

I ran:
mvn package
java -cp target/test-1.0-SNAPSHOT.jar Chat

**Comment by BrennanConroy** [comment]
cc @mikaelm12

**Comment by BrennanConroy** [comment]
Feel free to reopen if you're still having issues.
