### ISSUE TITLE
Getting 500 error when I put Objects in Http Response

### ISSUE THREAD

**Issue by EmpeRoar** [dotnet/AspNetCore.Docs#18776]
[Enter feedback here]
Using asp.net Net5.0, 

If I put BadRequest(new { message = ex.message }) this throws this error.

but string has no problem, example. BadRequest("error here")

```
 An unhandled exception has occurred while executing the request.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Microsoft.AspNetCore.WebUtilities.FileBufferingWriteStream.DrainBufferAsync(System.IO.Pipelines.PipeWriter, System.Threading.CancellationToken)'.
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.TextOutputFormatter.WriteAsync(OutputFormatterWriteContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
Solved

**Comment by RonaldRizkDev** [comment]
how was it solved?  i am having the same issue, and i do not see any updates that would fix this

**Comment by davidfowl** [comment]
@RonaldRizkDev by using the right versions of things. Whenever you get a method missing exception 99% of the time it's because you are doing something like mixing up preview versions of packages and the framework. If you're using previewX, make sure you update to previewX everywhere as breaking changes tend to occur more during previews than otherwise.

In the above case, @EmpeRoar was on preview5 of https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/ but had preview4 of net5 installed.

**Comment by RonaldRizkDev** [comment]
@davidfowl   thank you, but that is not the issue.  i was behind, i only had preview 4 installed, so i corrected that. i now have preview 5 installed, however, i am still getting the same issue.  i have not been able to run a version of Microsoft.AspNetCore.Authentication.JwtBearer beyond preview 3 because it tells me: 
Message=Method not found: 'Microsoft.AspNetCore.Authentication.AuthenticationBuilder Microsoft.AspNetCore.Authentication.AuthenticationBuilder.AddScheme(System.String, System.String, System.Action`2<System.__Canon,!!2>)'.
  Source=Microsoft.AspNetCore.Authentication.JwtBearer
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.JwtBearerExtensions.AddJwtBearer[TService](AuthenticationBuilder builder, String authenticationScheme, String displayName, Action`2 configureOptions)
   at Microsoft.Extensions.DependencyInjection.JwtBearerExtensions.AddJwtBearer(AuthenticationBuilder builder, String authenticationScheme, String displayName, Action`1 configureOptions)
   at Microsoft.Extensions.DependencyInjection.JwtBearerExtensions.AddJwtBearer(AuthenticationBuilder builder, String authenticationScheme, Action`1 configureOptions)
   at Microsoft.Extensions.DependencyInjection.JwtBearerExtensions.AddJwtBearer(AuthenticationBuilder builder, Action`1 configureOptions)
   at qube.endpoint.games.Startup.ConfigureServices(IServiceCollection services) in D:\Development\qube.gg\Engine\endpoints\qube.endpoint.games\Startup.cs:line 126
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at qube.endpoint.games.Program.Main(String[] args) in D:\Development\qube.gg\Engine\endpoints\qube.endpoint.games\Program.cs:line 11

and after i updated yesterday, all of my endpoints fail with a 500 with the same error he was getting above.

**Comment by davidfowl** [comment]
That’s a totally different error though right? Still likely a similar issue though...

**Comment by RonaldRizkDev** [comment]
yes and no.  i am getting two different missing function errors.  the one he is getting in this thread, and the jwt one.  maybe i am conflating to different problems.  but my .net preview version is 5 and i am up to date on my preview nuget packages, except the jwt because of the error i am getting in that one

**Comment by davidfowl** [comment]
It’s not the same error but if you can provide steps to reproduce I’ll try to find your version mismatch

**Comment by RonaldRizkDev** [comment]
@davidfowl   You were right, i found the issue, it was a mismatch, thank you for all your assistance
