### ISSUE TITLE
Linux OS with .NET- The configured user limit (128) on the number of inotify instances has been reached

### ISSUE THREAD

**Issue by travisgosselin** [dotnet/AspNetCore.Docs#19814]
This issue is directly related to and a followup of https://github.com/dotnet/aspnetcore/issues/7531 since that issue has been locked. The same issue occurs now in .NET Core 3.1. Following the previous thread, I was able to specify a different user in my Dockerfile to limit this problem which occurs when putting too many docker containers on the same host that are using the same user UID. Our teams now use a randomized UID to ensure each immutable build has its own ID:

```
RUN useradd --uid $(shuf -i 2000-65000 -n 1) app
USER app
```

This works to limit the issue, but the problem still continues if you intend to run the same instance of that immutable container with 9 or more instances on the same container orchestrator host. For example if I use the following image: "FROM mcr.microsoft.com/dotnet/core/aspnet:3." to run a base default / empty ASP.NET Core application with the following Program.cs (and usage of zero-configuration files):

```
Host.CreateDefaultBuilder(args)
                .ConfigureWebHost(builder =>
                {
                    builder
                        .UseKestrel()
                        .UseStartup<Startup>();
                });
```

Run a default app in the container above, and attach your shell and execute the following to count the number of watchers:
```
apt-get install lsof
lsof | grep inotify
```
.NET Core 3.1 shows me generally 15 or 16, while .NET Core 2.1 default app shows more like 40.
If I am running 8 containers each taking at least 15 instances of the 128 limit - I run out pretty quickly.

General concerns:
1. Scaling is the first concern I have for obvious reasons (depending on my placement strategy). Is the expectation that I should be increasing this limit on my orchestrator hosts to allow for this?
2. With a default execution of ASP.NET Core 3.1 that uses no configuration files, why am I seeing 15 instances? Typically speaking in a container there is very little reason I even want to watch files (especially not configuration files) since its entirely immutable. Is there a way to entirely turn off the inotify watcher instances all together (which would solve this problem entirely)? Or is there an underlying bug in ASP.NET Core here?

***EDIT by @Rick-Anderson***  #28387 mitigates the problem.

---
[Associated WorkItem - 64021](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64021)

**Comment by BrennanConroy** [comment]
We should look into adding a doc about ulimit on mac and linux.

Also, mention using the polling file watcher to reduce inotify instances.

**Comment by Rick-Anderson** [comment]
@travisgosselin what doc should this go in?

**Comment by travisgosselin** [comment]
Good question @Rick-Anderson - Ideally it wouldn't be a concern at all and be fixed, but for the Docs specifically, it seems prudent to call out these best practices out in any location that discusses Dockerfile usage patterns for ASP.NET Core. Existing, "The Dockerfile" section here might be a starting place; it already indicates COPY of csproj and sln files as a good practice for docker layer caching (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.1). Calling out additionally some of the security practices described here for not running as root and the side effects from a port security perspective (i.e. has to be above port 1000) might make sense?

Perhaps here as well? https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows
Or perhaps this belongs closer to security? A new page as a sibling or close to something like this related to hosting: https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1

**Comment by vasnab** [comment]
+1

**Comment by Rick-Anderson** [comment]
@BrennanConroy @travisgosselin  several places report fixing this via `reloadOnChange: false);`

`.AddJsonFile($"appsettings.json", optional: true, reloadOnChange: false);`

See https://stackoverflow.com/a/56547116/502537

**Comment by BrennanConroy** [comment]
Sure, that could be a solution if you don't care about refreshing config on file change.

**Comment by Rick-Anderson** [comment]
@travisgosselin  is  the following enough to fix the problem?

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            config.AddJsonFile("appsettings.json",
                optional: true,
                reloadOnChange: false);
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
}
```

Or do you need to follow https://stackoverflow.com/a/56547116/502537 ?  and not use the default builder?

**Comment by Rick-Anderson** [comment]
Per @paillave [here](https://github.com/dotnet/aspnetcore/issues/8449#issuecomment-514636948)

 `echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
 this will increase the amount of authorized instances as too many may be taken by vs code addons

**Comment by travisgosselin** [comment]
Thanks for getting back to this @Rick-Anderson . All the suggestions you provide since my last post definitely help, and are actions I've taken across our services. That being said, even with my earlier investigation and initial notes, there seems to be no option to eliminate all watchers completely, even when setting reloadOnChange false. Generally speaking, I have that disabled anyhow, since this is inside a container, I'm not sure how useful it is. At the end of the day, all this information should be documented (if not fixed) indicating that you should NOT use the root user as a best practice, and the possible implications of scaling your service in PROD resulting in possible startup failure (if strategy places too many on a large host).

**Comment by johnnyreilly** [comment]
We're also bumping on this issue with .NET Core 3.1 and Function apps.

**Comment by Rick-Anderson** [comment]
See [this comment by `@Tratcher`](https://github.com/dotnet/AspNetCore.Docs/pull/22391)

**Comment by kanadaj** [comment]
@Tratcher would it be unreasonable to expect the Docker image to have DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false by default?

**Comment by Tratcher** [comment]
@kanadaj because you don't expect the config files to change without at least restarting? Seems reasonable.

@bradygaster @sebastienros do you know where to file that?

**Comment by sebastienros** [comment]
Should it be in the VS docker templates? Like we asked to change the App Service setting for forward proxy headers?

**Comment by johnnyreilly** [comment]
This sounds like a good idea ,I've  an issue related to this open on that repo here: https://github.com/microsoft/vscode-dev-containers/issues/418

**Comment by blackie1019** [comment]
> @Tratcher would it be unreasonable to expect the Docker image to have DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false by default?

Totally agreed with this suggestion. 

Because not all linux or emulator supported this feature and this is not a essential function for ASP.NET Core in any version, it's absolutely turn to false for default for redundant code put into the non sense block without the essential technical support. 

Considering the QEMU not support this, and Apple M1 + .NET Core with Linux-x64 container running on this emulator I strongly recommend put this setting to False by default to help more rookie of ASP.NET Core without the pointless survey/research to play and learn ASP.NET Core on both Intel and ARM CPU on macOS system.

**Comment by Rombersoft** [comment]
I have the same problem on NET 6. I don't use docker and run the application on a Linux host.
But my error happens in the code:
```
WebApplicationBuilder builder = WebApplication.CreateBuilder();
```
Exception is:

```
System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder()
```
Is any suggestion?

**Comment by Rombersoft** [comment]
I understood that this problem is in VS Code.
So I have 3 cases:
1. VS Code is loaded and Rider IDE is unloaded: my application has this exception when I run it from VS Code.
2. VS Code & Rider are loaded and have opened the same solution (.sln): my application has this exception when I run it from any IDE, it does not mean VS Code or Rider.
3. VS Code is unloaded and Rider IDE is loaded; my application does not have this exception!!! WTF???

I see that VS Code offer me to create launch.json file:
```
{
    // Используйте IntelliSense, чтобы узнать о возможных атрибутах.
    // Наведите указатель мыши, чтобы просмотреть описания существующих атрибутов.
    // Для получения дополнительной информации посетите: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/GUI/TerminalUI/bin/Debug/net6.0/TerminalUI.dll",
            "args": [],
            "cwd": "${workspaceFolder}/GUI/TerminalUI",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```
On another website I read that VS Code runs the application on docker but I don't see where in launch.json it is directed that application must run in docker

**Comment by smorokin** [comment]
> On another website I read that VS Code runs the application on docker but I don't see where in launch.json it is directed that application must run in docker
 
@Rombersoft: This is only true if you use the dev container feature of it. You would have a .devcontainer folder in your project if it is the case

**Comment by alexkreskiyan** [comment]
In my case of simple linux host (no problem with containers yet), handled the problem with:
https://github.com/mikesart/inotify-info - to identify inotify consumers
Updated /etc/sysctl.conf with:
```
fs.inotify.max_user_instances=1024
fs.inotify.max_user_watches=1048576
```
Important to note, initially problem happened due to limit of user instances, set to 128, not limit of user watches

**Comment by Rick-Anderson** [comment]
@travisgosselin see what @alexkreskiyan  has above this. Looks useful.

**Comment by travisgosselin** [comment]
> @travisgosselin see what @alexkreskiyan has above this. Looks useful.

Sure, I would imagine that additional limit would be important as well, though I haven't run into that myself specifically. I have increased the user_watches on our systems as a workaround in my case.

**Comment by andrewhornsby-bjss** [comment]
We had this problem running tests on our devops linux self-hosted build agent. Interestingly we didn't get the issue on the the cloud agent, so maybe it is configured differently.

The above fix has solved the problem for us though. Thanks @alexkreskiyan!

**Comment by LanAnh002** [comment]
I have same problem but seem can't not resolve:
blazor.webassembly.js?v=1:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
I try to fix this issue by four way:
1. change config: reloadOnChange => false
2. Change variable environment DOTNET_USE_POLLING_FILE_WATCHER => true
3. Change variable environment DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=> false
4. Change max user instance: 
 ・echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  ・echo 512 > /proc/sys/fs/inotify/max_user_instances
=> It's not work

**Comment by macias** [comment]
@LanAnh002 do you use step (2) this way? I put this right at the start of my program and I didn't hit this bug in a long time.
```
        Environment.SetEnvironmentVariable("DOTNET_hostBuilder:reloadConfigOnChange", "false");
        var builder = WebApplication.CreateBuilder(args);
```

**Comment by LanAnh002** [comment]
@macias 
Your way seem like my way 1:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/28666400/2d49e19e-de4b-4235-946b-99b08fd8a152)

**Comment by macias** [comment]
@LanAnh002 it will cost you nothing, could you please put "my" first line as your first one?

**Comment by LanAnh002** [comment]
@macias 
I try add your first line as my first one but it didn't work:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/28666400/afa87719-ef4c-4b69-8e01-5788a885a19d)

**Comment by baylavdev** [comment]
Hi everyone! I'd like to work on this issue and add the necessary documentation regarding the Linux inotify limit for `dotnet watch`.
