### ISSUE TITLE
Can't change a collection while iterating

### ISSUE THREAD

**Issue by Frankofoedu** [dotnet/AspNetCore.Docs#19935]
This line when creating a custom user factory throws an error.
`identity.RemoveClaim(existingClaim)`.

Making the roleclaims collection a new copy of the identityclaims collection should fix it

`var roleClaims = identity.FindAll(identity.RoleClaimType).ToArray`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio#server-app-configuration)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Frankofoedu ... I can't repro that error with 3.x. With the `identity.RemoveClaim(existingClaim)` line, final claims are (my test roles are "CustomRole" and "Another Role") ...

<img width="233" alt="Capture" src="https://user-images.githubusercontent.com/1622880/93772844-f03f0a80-fbe4-11ea-86d5-f4ff326952d5.PNG">

Comment out the line, and the original `role` claim is there ...

<img width="238" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/93772850-f208ce00-fbe4-11ea-965b-f95d4d591e9a.PNG">

> throws an error

Can you provide the stack trace? ... and confirm that you're using the code exactly as it appears in the topic?

Also, let's confirm versioning ...

* Are you reporting this for framework version 3.x or 5.0 RC1?
* Latest version of the IdS package (`Microsoft.AspNetCore.ApiAuthorization.IdentityServer`) for 3.x is `3.1.8`, but my test app is on `3.1.3`. That's just happens to be where I left off with testing. What version of that package are you using? 

Also, I do see one thing (unrelated to your issue here) that should be done. The part of the document that explains how to add the factory to the client app doesn't also tell readers that they must [configure Identity Server](https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-identity-server#configure-identity-server) in order to make roles work (i.e., they must come down from the server in order to be processed, but the section doesn't make that clear).

**Comment by Frankofoedu** [comment]
@guardrex Thanks for replying back.

>Can you provide the stack trace? ... and confirm that you're using the code exactly as it appears in the topic?

Here is the stack trace from the browser. 

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator[[System.Security.Claims.Claim, System.Security.Claims, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator[[System.Security.Claims.Claim, System.Security.Claims, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Security.Claims.ClaimsIdentity.FindAll(String type)+MoveNext()
   at CustomUserFactory.CreateUserAsync(RemoteUserAccount account, RemoteAuthenticationUserOptions options) in C:\Users\Frank\source\repos\GISProject\GISProject.Web\Client\CustomUserFactory.cs:line 29
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<GetAuthenticatedUser>d__26[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<GetUser>d__25[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<CompleteSignInAsync>d__19[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<ProcessLogInCallback>d__84[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<OnParametersSetAsync>d__82[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)






>Are you reporting this for framework version 3.x or 5.0 RC1?
> Latest version of the IdS package (Microsoft.AspNetCore.ApiAuthorization.IdentityServer) for 3.x is 3.1.8, but my test app is on 3.1.3. That's just happens to be where I left off with testing. What version of that package are you using?


dotnet 5.0.100-preview.7.20366.6
I will try it in 5.0RC and give feedback.
These are the packages I have installed in the server and wasm project

![claim](https://user-images.githubusercontent.com/20884394/93852840-a9b3e380-fcaa-11ea-87fe-f275f5af5bae.png)

![claims wasm](https://user-images.githubusercontent.com/20884394/93852929-d7009180-fcaa-11ea-8d87-036d2d7b1922.png)

>Also, I do see one thing (unrelated to your issue here) that should be done. The part of the document that explains how to add the factory to the client app doesn't also tell readers that they must configure Identity Server in order to make roles work (i.e., they must come down from the server in order to be processed, but the section doesn't make that clear).

DOes that mean we have to configure services like this
 `services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options => {
        options.IdentityResources["openid"].UserClaims.Add("name");
        options.ApiResources.Single().UserClaims.Add("name");
        options.IdentityResources["openid"].UserClaims.Add("role");
        options.ApiResources.Single().UserClaims.Add("role");
    });

JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("role");`

and still configure a profile service class?

**Comment by Frankofoedu** [comment]
Just tested with rc1 and the error still came up

**Comment by guardrex** [comment]
> and still configure a profile service class?

No, configuring a Profile Service counts as "configuring Identity Server." There are two approaches, and that's one of them.

It might be explained by the version ... maybe. I'm a bit surprised that I can't repro that with a 3.x app.
I'll add a cross-link to my issue for the 5.0 docs work and deal with this issue when I work that. I should be starting work on that this week. Go ahead and use ...

```csharp
var roleClaims = identity.FindAll(identity.RoleClaimType).ToArray
```

... since that's working for you.

**Comment by guardrex** [comment]
I marked it on the issue. I'll place this on hold to see if the change ends up in the doc. If so, this issue will automatically close when the PR merges.

Thanks for reporting this.
