### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]  Failed to authenticate HTTPS connection.

### ISSUE THREAD

**Issue by RhysWilliams647** [dotnet/AspNetCore.Docs#20030]
Followed instructions per documentation to setup https with docker-compose dotnetcore app.  However when visiting the site via the https port I get ERR_EMPTY_RESPONSE in chrome.  I then checked the logs in the container to get the below error:

```
Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]

Failed to authenticate HTTPS connection.

System.IO.IOException: The handshake failed due to an unexpected packet format.

at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)

at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)

at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)

at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)

at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)

at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)

at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)

at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)

at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)

at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)

at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)

```

Link to repository.

[https://github.com/RhysWilliams647/MicroservicesApp](url)

Using 
dotnetcore 3.1
Docker for windows 2.3.0.5 (48029)
WSL2 integration Ubuntu 20.04

Docker for windows shows app is listening on https port 8001.

![Capture2](https://user-images.githubusercontent.com/60811036/94460920-56152e80-01b1-11eb-83bb-353a43bbc95f.PNG)

![Capture](https://user-images.githubusercontent.com/60811036/94460865-43025e80-01b1-11eb-80a4-78aec2fc1756.PNG)

Http works without issue.  I have removed the kestrel sections in appsettings.json and ran the app without docker and successfully accessed https.

Ran the below commands and setup the aspnetapp.pfx certificate which asked me to trust the certificate.  Checked aspnetapp.pfx is in expected location.

dotnet dev-certs https --clean
dotnet dev-certs https --trust -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p Pa$$w0rd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf7806c-d9e4-1811-3308-b5efb6f159f0
* Version Independent ID: 2117dfa1-9e6d-2bc2-2348-e792f3c81806
* Content: [Hosting ASP.NET Core image in container using docker compose with HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-compose-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ravipal
* Microsoft Alias: **ravipal**

**Comment by Rick-Anderson** [comment]
4 K PV/ month

**Comment by RhysWilliams647** [comment]
Hi, sorry what further information do you need? 

Cheers

**Comment by RhysWilliams647** [comment]
I managed to get this working with one of my other Microservices therefore comparing the two.  Must be local issue.  Sorry for wasting your time

Cheers
