### ISSUE TITLE
Synchronous JS interop: casting to IJSInProcessObjectReference throws

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/AspNetCore.Docs#20103]
Looking at the preliminary docs here:
https://github.com/dotnet/AspNetCore.Docs/blob/stevesa/blazor-wasm-perf/aspnetcore/blazor/webassembly-performance-best-practices.md#consider-making-synchronous-calls

Using .NET 5: 5.0.0-rc.2.20474.6

In my Blaror WASM app I have a service like this:
```
public class WebcamService : IWebcamService, IAsyncDisposable
    {
        private readonly Lazy<Task<IJSObjectReference>> _moduleTask;

        public WebcamService(IJSRuntime jsRuntime)
        {
            _moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>(
               "import", "./jsinterop/webcam.js").AsTask());
        }

        public async Task StartVideo(WebcamOptions options)
        {
            var module = await _moduleTask.Value;
            ((IJSInProcessObjectReference)module).InvokeVoid("startVideo", options);
        }

        public async Task TakePicture()
        {
            var module = await _moduleTask.Value;
            ((IJSInProcessObjectReference)module).InvokeVoid("takePicture");
        }

        public async ValueTask DisposeAsync()
        {
            if (_moduleTask.IsValueCreated)
            {
                var module = await _moduleTask.Value;
                await module.DisposeAsync();
            }
        }
    }
```

When calling e.g. the StartVideo method, the code throws:

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at ConfTool.Client.Webcam.WebcamService.StartVideo(WebcamOptions options) in C:\sources\blazor-webassembly-demo\Client\Webcam\WebcamService.cs:line 20
   at ConfTool.Client.Webcam.Webcam.StartVideoAsync() in C:\sources\blazor-webassembly-demo\Client\Webcam\Webcam.razor:line 40
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

Not sure what could be wrong here.

Repro can be found here:
https://github.com/thinktecture/blazor-webassembly-demo/blob/net5-sync-js/Client/Webcam/WebcamService.cs#L20

Thanks!

**Comment by Rick-Anderson** [comment]
@pranavkm @SteveSandersonMS

**Comment by guardrex** [comment]
@ChristianWeyer ... Please open that for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by guardrex** [comment]
btw @ChristianWeyer ... Steve is working on some guidance pertaining to that API on ...

https://github.com/dotnet/AspNetCore.Docs/pull/20057

... check the diff to see if his example and remarks help.

However, don't ask about your issue here :point_up: on the docs PR. It's best to address your question with a product unit issue.
