### ISSUE TITLE
Could not find 'VirtualizedComponent' in 'window'.

### ISSUE THREAD

**Issue by ngpns** [dotnet/AspNetCore.Docs#20105]
Hi there, 
I'm trying to implement Blazor virtualization component on my project (ASP.NET Core 3.1 webassembly). But I faced the following bug. 
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'VirtualizedComponent' in 'window'.
      Error: Could not find 'VirtualizedComponent' in 'window'.
          at https://localhost:4001/_framework/blazor.webassembly.js:1:9130
          at Array.forEach (<anonymous>)
          at p (https://localhost:4001/_framework/blazor.webassembly.js:1:9090)
          at https://localhost:4001/_framework/blazor.webassembly.js:1:9800
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:4001/_framework/blazor.webassembly.js:1:9773)
          at _mono_wasm_invoke_js_marshalled (https://localhost:4001/_framework/wasm/dotnet.3.2.0.js:1:171294)
          at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
          at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
          at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
Microsoft.JSInterop.JSException: Could not find 'VirtualizedComponent' in 'window'.
Error: Could not find 'VirtualizedComponent' in 'window'.
    at https://localhost:4001/_framework/blazor.webassembly.js:1:9130
    at Array.forEach (<anonymous>)
    at p (https://localhost:4001/_framework/blazor.webassembly.js:1:9090)
    at https://localhost:4001/_framework/blazor.webassembly.js:1:9800
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:4001/_framework/blazor.webassembly.js:1:9773)
    at _mono_wasm_invoke_js_marshalled (https://localhost:4001/_framework/wasm/dotnet.3.2.0.js:1:171294)
    at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x31826e0 + 0x00034> in <filename unknown>:0 
  at Ng.eCommerce.AdminPanel.Pages.Tapan`1[TItem].OnAfterRenderAsync (System.Boolean firstRender) [0x00071] in C:\Users\tpn\source\repos\NG.eCommerce\ng.ecommerce.adminpanel\Pages\Tapan.cs:77 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2e588c8 + 0x000b6> in <filename unknown>:0

**Comment by guardrex** [comment]
Hello @ngpns ... FYI, please open new issues using the **This page** feedback button and form at the bottom of the English-US topic, which will add metadata to the issue.

For this issue tho, you'll need to open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... and in addition to the error, show them your component code, too.
