### ISSUE TITLE
adding documentation for `@bind-Value`

### ISSUE THREAD

**Issue by neil-rubens** [dotnet/AspNetCore.Docs#21338]
`@bind-Value` seems to be quite handy for a two-way binding; but I couldn't find mentioning of it on this page.

p.s. was using it in:
`<InputCheckbox @bind-Value=MyCheckBoxStatus />`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @neil-rubens ... It's called "binding to a component parameter." `Value` is the parameter (property) in this case. It's covered here at ...

https://docs.microsoft.com/aspnet/core/blazor/components/data-binding#binding-with-component-parameters

The `InputCheckBox` component is covered in the *Forms and Validation* topic because it's used in forms ...

https://docs.microsoft.com/aspnet/core/blazor/forms-validation

**Comment by neil-rubens** [comment]
@guardrex thank you for the explanations; makes sense now.


I'll add a little bit details in case somebody else makes the same mistake as myself.

In https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0#binding-with-component-parameters

I misunderstood that `@bind-{PROPERTY OR FIELD}` refers to the property of the component itself (obvious in retrospect) and no the property of the enclosing razor page.

# Wrong Way

So I first wrote and got a runtime error (I've attached it at the bottom of the page; for readability): 
```
<InputCheckbox @bind-MyCheckBoxStatus=MyCheckBoxStatus />

@code{
public bool MyCheckBoxStatus {get; set;} = false;
}

```

# Right Way

As pointed out by @guardrex the binded value refer to the component itself (in my case, InputCheckBox) and not the enclosing class (MyClass.razor); so what should be done is binding the  InputCheckBox.`Value` to MyClass.`MyCheckBoxStatus` which could be done via
`<InputCheckbox @bind-Value=MyCheckBoxStatus/>`


> Gets or sets the value of the input. This should be used with two-way binding.
> ```
> [Microsoft.AspNetCore.Components.Parameter]
> public TValue Value { get; set; }
> ```
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputbase-1.value?view=aspnetcore-5.0#Microsoft_AspNetCore_Components_Forms_InputBase_1_Value

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputbase-1.value?view=aspnetcore-5.0#Microsoft_AspNetCore_Components_Forms_InputBase_1_Value


# Error

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Microsoft.AspNetCore.Components.Forms.InputCheckbox requires a value for the 'ValueExpression' parameter. Normally this is provided automatically when using 'bind-Value'.
System.InvalidOperationException: Microsoft.AspNetCore.Components.Forms.InputCheckbox requires a value for the 'ValueExpression' parameter. Normally this is provided automatically when using 'bind-Value'.
   at Microsoft.AspNetCore.Components.Forms.InputBase`1[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```
