### ISSUE TITLE
options.EnableLdap throws DirectoryOperationException: An operation error occurred

### ISSUE THREAD

**Issue by freerider7777** [dotnet/AspNetCore.Docs#21491]
(RHEL 8.2)
I've tried many combinations for (with/without password, machine account and user account)
options.EnableLdap

But it fails on incoming request (with wrong credentials the service does not start)

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.
         at System.DirectoryServices.Protocols.LdapConnection.EndSendRequest(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.Negotiate.LdapAdapter.RetrieveClaimsAsync(LdapSettings settings, ClaimsIdentity identity, ILogger logger)
         at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
dbug: Microsoft.AspNetCore.HttpsPolicy.HstsMiddleware[1]
      The request is insecure. Skipping HSTS header.
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path /Home/Error does not match a supported file type
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      1 candidate(s) found for the request path '/Home/Error'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'TestAD2.Controllers.HomeController.Error (TestAD2)' with route pattern '{controller=Home}/{action=Index}/{id?}' is valid for the request path '/Home/Error'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'TestAD2.Controllers.HomeController.Error (TestAD2)'
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
      An exception was thrown attempting to execute the error handler.
      System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.
         at System.DirectoryServices.Protocols.LdapConnection.EndSendRequest(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.Negotiate.LdapAdapter.RetrieveClaimsAsync(LdapSettings settings, ClaimsIdentity identity, ILogger logger)
         at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM6CV9DFB5D7", Request id "0HM6CV9DFB5D7:00000003": An unhandled exception was thrown by the application.
      System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.
         at System.DirectoryServices.Protocols.LdapConnection.EndSendRequest(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.Negotiate.LdapAdapter.RetrieveClaimsAsync(LdapSettings settings, ClaimsIdentity identity, ILogger logger)
         at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @freerider7777 ... Best on this one to ask the product unit directly at ...

https://github.com/dotnet/aspnetcore/issues

... then if you find coverage that you feel should be called out ... perhaps a **_gotcha_** 😈 ... or something really wrong with the topic's remarks, leave a comment back on this issue to re-open it for work.

I recommend cross-linking this issue in your new product unit issue opening comment so that this one won't get lost.

**Comment by freerider7777** [comment]
Ok, thanks... I thought maybe something is undocumented, but it seems to be a new and maybe buggy feature...

**Comment by guardrex** [comment]
They'll investigate and let you/us know. It just won't really be seen over here. You'll get a better/faster response by opening over there. That's the repo they work the potential 🐞 *bugs* 🐞 on.

**Comment by freerider7777** [comment]
Thanks :) Cross-link https://github.com/dotnet/aspnetcore/issues/30032

**Comment by neomasterhub** [comment]
I had the same error, I added the following parameter, now it works

```c#
.AddNegotiate(options =>
{
    options.EnableLdap(settings =>
    {
        settings.Domain = ldapOptions.Domain;
        settings.EnableLdapClaimResolution = ldapOptions.EnableLdapClaimResolution;
        settings.IgnoreNestedGroups = ldapOptions.IgnoreNestedGroups;
        settings.LdapConnection = new GetLdapConnectionService(ldapOptions).Get();
        
       settings.LdapConnection.SessionOptions.ReferralChasing = ReferralChasingOptions.None; // <--- (!)
    });
});
```
![image](https://github.com/dotnet/AspNetCore.Docs/assets/59305081/87d6cadd-4312-412a-863f-09886bcd1327)
