### ISSUE TITLE
Using #app works locally but when published to AZURE fails (core 3.1 -> 5.0 migration)

### ISSUE THREAD

**Issue by erikthysell** [dotnet/AspNetCore.Docs#21573]
[Enter feedback here]
Trying to migrate a asp.net backed Blazor webassembly app 3.1 -> 5.0: When using the guide and performing change 6. under "Update Blazor WebAssembly projects" [here](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio):

```
-builder.RootComponents.Add<App>("app");
+builder.RootComponents.Add<App>("#app");

```
it works when I am debugging locally but when published to AZURE it fails with the following message:

> blazor.webassembly.js:1 Microsoft.JSInterop.JSException: Could not find any element matching selector '#app'.

If i change it back it fails locally as well with the same error message.
It seems as if it is not included when publishing to AZURE.
(Visual studio 16.8.4, .NET 5.0.3)

Stack trace from Chromes console (replaced specifics):
blazor.webassembly.js:1 Microsoft.JSInterop.JSException: Could not find any element matching selector '#app'.
blazor.webassembly.js:1 Error: Could not find any element matching selector '#app'.
at Object.t.attachRootComponentToElement (https://foosite.azurewebsites.net/_framework/blazor.webassembly.js:1:11663)
at Object.window.Blazor._internal.attachRootComponentToElement (https://foosite.azurewebsites.net/_framework/blazor.webassembly.js:1:63481)
at Object.invokeJSFromDotNet (https://foosite.azurewebsites.net/_framework/blazor.webassembly.js:1:3797)
at Object.w [as invokeJSFromDotNet] (https://foosite.azurewebsites.net/_framework/blazor.webassembly.js:1:64287)
at _mono_wasm_invoke_js_blazor (https://foosite.azurewebsites.net/_framework/dotnet.5.0.3.js:1:190800)
at do_icall (https://foosite.azurewebsites.net/_framework/dotnet.wasm:wasm-function[10596]:0x194e4e)
at do_icall_wrapper (https://foosite.azurewebsites.net/_framework/dotnet.wasm:wasm-function[3305]:0x79df9)
at interp_exec_method (https://foosite.azurewebsites.net/_framework/dotnet.wasm:wasm-function[2155]:0x44ad3)
at interp_runtime_invoke (https://foosite.azurewebsites.net/_framework/dotnet.wasm:wasm-function[7862]:0x12efff)
at mono_jit_runtime_invoke (https://foosite.azurewebsites.net/_framework/dotnet.wasm:wasm-function[7347]:0x118e5f)
at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeJS(String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
at Microsoft.JSInterop.JSInProcessRuntime.Invoke[Object](String identifier, Int64 targetInstanceId, Object[] args)
at Microsoft.JSInterop.JSInProcessRuntime.Invoke[Object](String identifier, Object[] args)
at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.AddComponentAsync(Type componentType, String domElementSelector, ParameterView parameters)
at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken cancellationToken)
at MyFOOSolution.Client.Program.Main(String[] args)
at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint(String assemblyName, String[] args)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by erikthysell** [comment]
Sorry... a simple re-push -> rebuild -> redeploy seems to have solved it.
