### ISSUE TITLE
Extra package needed to generate controller successfully

### ISSUE THREAD

**Issue by dfuenzalida** [dotnet/AspNetCore.Docs#21662]
While following the tutorial, I found the instructions for **VSCode / Visual Studio for Mac** in the section [Scaffold a Controller](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code#scaffold-a-controller) didn't work until I added one extra package, reported by the `aspnet-codegenerator` tool:

The commands from the tutorial are:

```
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet tool install -g dotnet-aspnet-codegenerator
dotnet tool update -g dotnet-aspnet-codegenerator
dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
```
but the last command failed with:

```
$ dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
Building project ...
Finding the generator 'controller'...
Running the generator 'controller'...
To scaffold, install the following Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.SqlServer.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:04.26
```

running `dotnet add package Microsoft.EntityFrameworkCore.SqlServer` allowed me to continue:

```
$ dotnet add package Microsoft.EntityFrameworkCore.SqlServer
  Determining projects to restore...
... output elided ...

$ dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
Building project ...
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'TodoItem'
Added Controller : '/Controllers/TodoItemsController.cs'.
RunTime 00:00:07.97
```

Runtime information:
* Ubuntu 20.04.2 LTS 64-bit
*  dotnet --version: `5.0.200`
* Visual Studio Code 1.53.2

dotnet info:

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/denis/bin/dotnet-sdk-5.0.200-linux-x64/sdk/5.0.200/

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.200 [/home/denis/bin/dotnet-sdk-5.0.200-linux-x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [/home/denis/bin/dotnet-sdk-5.0.200-linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.3 [/home/denis/bin/dotnet-sdk-5.0.200-linux-x64/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dfuenzalida  thanks for the excellent write up of the problem and solution.
