### ISSUE TITLE
Please update AspNetCore.Docs\aspnetcore\mvc\views\partial\sample\PartialViewsSample to .net 5.0

### ISSUE THREAD

**Issue by LimingRenPA** [dotnet/AspNetCore.Docs#22089]
# Issue description

The project does not work with  .net 5.0, please update it.

Topic:  [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-5.0)
Sample: [PartialViewsSample](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/views/partial/sample/PartialViewsSample)

Update of issue description from WadePickett:
- When re-targeted to 5.0 the app sample throws exceptions such as "System.InvalidOperationException: 'Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. "
- The sample compiles and runs as is target 2.2.  The sample currently targets 2.2 and does not appear to have been updated to either 3.1 nor 5.0.

**Additional details originally submitted by issue creator:**
If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\repos\AspNetCore.Docs\aspnetcore\mvc\views\partial\sample\PartialViewsSample\PartialViewsSample.csproj'.
d:\repos\AspNetCore.Docs\aspnetcore\mvc\views\partial\sample\PartialViewsSample\PartialViewsSample.csproj(0,0)
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OmniSharp.MSBuild.Logging.MSBuildDiagnostic.CreateFrom(BuildErrorEventArgs args) in D:\a\1\s\src\OmniSharp.MSBuild\Logging\MSBuildDiagnostic.cs:line 39
   at OmniSharp.MSBuild.Logging.MSBuildLogger.OnError(Object sender, BuildErrorEventArgs args) in D:\a\1\s\src\OmniSharp.MSBuild\Logging\MSBuildLogger.cs:line 29
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.Execution.BuildManager.Build(BuildParameters parameters, BuildRequestData requestData)
   at Microsoft.Build.Execution.ProjectInstance.Build(String[] targets, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ILoggingService loggingService, Int32 maxNodeCount, IDictionary`2& targetOutputs)
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath, IReadOnlyDictionary`2 configurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 99
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Reload(ProjectLoader loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 140
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 315

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PartialViewsSample
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\repos\AspNetCore.Docs\aspnetcore\mvc\views\partial\sample\PartialViewsSample\PartialViewsSample.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\repos\AspNetCore.Docs\aspnetcore\mvc\views\partial\sample\PartialViewsSample\PartialViewsSample.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\repos\AspNetCore.Docs\aspnetcore\mvc\views\partial\sample\PartialViewsSample\PartialViewsSample.csproj'.
d:\repos\AspNetCore.Docs\aspnetcore\mvc\views\partial\sample\PartialViewsSample\PartialViewsSample.csproj(0,0)
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OmniSharp.MSBuild.Logging.MSBuildDiagnostic.CreateFrom(BuildErrorEventArgs args) in D:\a\1\s\src\OmniSharp.MSBuild\Logging\MSBuildDiagnostic.cs:line 39
   at OmniSharp.MSBuild.Logging.MSBuildLogger.OnError(Object sender, BuildErrorEventArgs args) in D:\a\1\s\src\OmniSharp.MSBuild\Logging\MSBuildLogger.cs:line 29
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.Execution.BuildManager.Build(BuildParameters parameters, BuildRequestData requestData)
   at Microsoft.Build.Execution.ProjectInstance.Build(String[] targets, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ILoggingService loggingService, Int32 maxNodeCount, IDictionary`2& targetOutputs)
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath, IReadOnlyDictionary`2 configurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 99
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Reload(ProjectLoader loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 140
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 315

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PartialViewsSample

**Comment by rogwool** [comment]
Same,   The framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.

**Comment by fiyazbinhasan** [comment]
@wadepickett I can take a look at it if needed

**Comment by rogwool** [comment]
Are using .net 2.2.  maybe wrIte an  exe to update them?
