### ISSUE TITLE
CustomUserFactory code

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#22507]
From @peterbozso on https://github.com/dotnet/AspNetCore.Docs/pull/22505 ...

> According to this comment: https://github.com/dotnet/aspnetcore/issues/24237#issuecomment-663085021

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
... also (if) `.ToArray`, a null check shouldn't be needed IIRC.

**Comment by guardrex** [comment]
Latest local test app that I have (I *think* ... I have a *gazillion* of them 😆) is 3.2 with the code working. @peterbozso, are you aware if this is a 5.0-only problem that didn't exist back in the 3.2 era? ... because it looks like the PU issue was for 5.0. It was just something that didn't get called out over here for docs.

**Comment by peterbozso** [comment]
Thank you @guardrex for taking the time to look at this one!

I am building an application on top of the 5.0 Blazor WebAssembly Hosted template with Identity Server.  In order to use roles on the client side, I incorporated the code from the docs, [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#custom-user-factory).
When I ran the application with it, I got this exception:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator[[System.Security.Claims.Claim, System.Security.Claims, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator[[System.Security.Claims.Claim, System.Security.Claims, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Security.Claims.ClaimsIdentity.FindAll(String type)+MoveNext()
   at Pagestash.Client.Services.IdentityServerAccountClaimsPrincipalFactory.CreateUserAsync(RemoteUserAccount account, RemoteAuthenticationUserOptions options) in C:\Users\peter\Repos\pagestash\src\Pagestash\Client\Services\IdentityServerAccountClaimsPrincipalFactory.cs:line 35
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<GetAuthenticatedUser>d__26[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<GetUser>d__25[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<CompleteSignInAsync>d__19[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<ProcessLogInCallback>d__84[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<OnParametersSetAsync>d__82[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
I started to look for a solution and stumbled upon [this issue](https://github.com/dotnet/aspnetcore/issues/24237).
After incorporating the proposed fix (`ToArray()` call) by [this comment](https://github.com/dotnet/aspnetcore/issues/24237#issuecomment-663085021), the Exception was not thrown again.
This was the point when I thought it'd make sense to add this fix to the code in the official docs, so I opened [this PR](https://github.com/dotnet/AspNetCore.Docs/pull/22505), which you've closed.
What's next? :)

**Comment by peterbozso** [comment]
Since then I also further simplified (by reducing neting by inverting if-s) and improved (by making it null-safe) the code from the docs. Feel free to incorporate it in the docs if you'd like to.
```csharp
public override async ValueTask<ClaimsPrincipal> CreateUserAsync(
    RemoteUserAccount account,
    RemoteAuthenticationUserOptions options)
{
    var user = await base.CreateUserAsync(account, options);

    if (user.Identity?.IsAuthenticated != true)
    {
        return user;
    }

    var identity = (ClaimsIdentity)user.Identity;

    var roleClaims = identity.FindAll(identity.RoleClaimType).ToArray();

    if (roleClaims.Length == 0)
    {
        return user;
    }

    foreach (var existingClaim in roleClaims)
    {
        identity.RemoveClaim(existingClaim);
    }

    var rolesElem = account.AdditionalProperties[identity.RoleClaimType];

    if (rolesElem is not JsonElement roles)
    {
        return user;
    }

    if (roles.ValueKind == JsonValueKind.Array)
    {
        foreach (var role in roles.EnumerateArray())
        {
            AddClaim(identity, role, options);
        }
    }
    else
    {
        AddClaim(identity, roles, options);
    }

    return user;
}

private void AddClaim(
    ClaimsIdentity identity,
    JsonElement jsonElement,
    RemoteAuthenticationUserOptions options)
{
    var value = jsonElement.GetString();
    if (value != null)
    {
        identity.AddClaim(new Claim(options.RoleClaim, value));
    }
}
```

**Comment by guardrex** [comment]
Let's take the `ToArray` and just check `Any` (Linq). I understand that many devs prefer flatter code ... simpler for deep nesting for sure. However, it's also longer code ... more scrolling. This level of nesting is reasonable. I'm sure if Javier felt the nesting was an issue that he would've submitted his bits without it. He also didn't null check `user.Identity`. If that's a real problem, please open a new issue for that, and I'll ping him to take a look.
