### ISSUE TITLE
The dotnet ef database update command throws an ArgumentException

### ISSUE THREAD

**Issue by russjr08** [dotnet/AspNetCore.Docs#23706]
Hello,

First, I'd like to apologize for opening an issue, as I do see there was quite a bit of discussion on this issue in #21780.

I am attempting to follow this tutorial to learn the basics of ASP .NET Core with MVC. The tutorial seems to be extremely well written, until the point where you're shown how to wire up a database (SqlLite for dev, SqlServer for prod)...

Specifically, the problem happens when the tutorial has you run `dotnet ef database update`, I receive the following stacktrace:

```
System.ArgumentException: Connection string keyword 'server' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Connection string keyword 'server' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.
```

Now, on the other issue linked, I see that apparently the generated ConnectionString is for an SqlServer and not for SQLite. Manually updating the ConnectionString to the one provided in [this comment](https://github.com/dotnet/AspNetCore.Docs/issues/21780#issuecomment-812790940) is the only thing that allows me to pass this step (though I'm assuming this change will make it so when trying to run in production mode it will still use SQLite?), so I'm curious if potentially the documentation needs updating.

Prior to this step, you're supposed to use scaffolding with the following command:

```
dotnet-aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries
```

Now, the table _does_ list that there is a `-sqlite` flag, but if you're not looking for it, you can easily miss it. After adding the flag, it still didn't seem to modify `appsettings.json` to have a different ConnectionString - and using another possible solution (leaving off the `-dc MvcMovieContext` fails due to not having a valid dataContext).

If I am just simply overlooking something, then that's fine - however I read over the prior steps an additional three times just to be sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> table _does_ list that there is a `-sqlite` flag,

Yup, that got dropped. It in a couple versions of this doc. It's still in the Razor Pages version.
