### ISSUE TITLE
Error with sample code for  Multiple option selection with <input> elements: Need a typeconverter?

### ISSUE THREAD

**Issue by pondybala** [dotnet/AspNetCore.Docs#23779]
[Enter feedback here]
Get an error for the sample code for  Multiple option selection with <input> elements:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type 'System.String[]' does not have an associated TypeConverter that supports conversion from a string. Apply 'TypeConverterAttribute' to the type to register a converter.
System.InvalidOperationException: The type 'System.String[]' does not have an associated TypeConverter that supports conversion from a string. Apply 'TypeConverterAttribute' to the type to register a converter.
   at Microsoft.AspNetCore.Components.BindConverter.ParserDelegateCache.MakeTypeConverterConverter[String[]]()
   at Microsoft.AspNetCore.Components.BindConverter.ParserDelegateCache.Get[String[]]()
   at Microsoft.AspNetCore.Components.EventCallbackFactoryBinderExtensions.CreateBinder[String[]](EventCallbackFactory factory, Object receiver, Action`1 setter, String[] existingValue, CultureInfo culture)
   at BlazorPilot.Shared.BindMultipleInput.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pondybala ... I can't repro that. Seems to be working here ...

<img width="525" alt="Capture" src="https://user-images.githubusercontent.com/1622880/140653520-d8c960eb-7e08-450d-8c84-978d75f7007e.PNG">

Are you on the 6.0 preview SDK (CLI) or using VS 2022 Preview?

**Comment by guardrex** [comment]
@pondybala ... I'm going to close because I think that you're using 5.0 but trying to adopt a 6.0 feature. This scenario is only covered in the 6.0 version of the article. .NET 6 will release next week; so if you hold on for that, this scenario will work for you.
