### ISSUE TITLE
Clarify framework registration of IJSRuntime

### ISSUE THREAD

**Issue by benoit160** [dotnet/AspNetCore.Docs#26038]
I followed the guide on how to use JSRuntime interrop, but cannot get it to work in my blazor wasm app

`            builder.Services.AddScoped<IJSRuntime, JSRuntime>();
`

and then in my razor page : 

`@inject IJSRuntime runtime
`

This throw an exception :
---> System.ArgumentException: Cannot instantiate implementation type 'Microsoft.JSInterop.JSRuntime' for service type 'Microsoft.JSInterop.IJSRuntime'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(ICollection`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, Boolean validateScopes)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.<>c__DisplayClass5_0.<.ctor>b__0()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.Build()
   at Company.WebApplication1.Program.Main(String[] args) in C:\Users\Ben\Desktop\SpaceBattles\SpaceBattles\Client\Program.cs:line 20

I suspects it is because the JSRuntime class doesn't expose any public constructor.. but then how to use it ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7ea38a-649b-303d-bebf-c701e216ba25
* Version Independent ID: 9e197a8b-2616-8363-0a15-38cac802e82e
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @benoit160 ... Clarify a few things ...

* What do you mean by "razor page"? ... do you mean Razor component? This topic only applies to Razor components.
* Why did you try to register the service? The topic doesn't call for that. You only need to inject the service because the framework already registers `IJSRuntime` in the service container.

**Comment by guardrex** [comment]
I think at a minimum that point about the framework registration should be called out. I'll take care of that.

Regardless of whatever else we might discuss here, leave this issue open ... it will close when the PR merges later.

**Comment by benoit160** [comment]
- Yes
- Sorry, indeed it works without registering the service

**Comment by guardrex** [comment]
Great ... ok ... I'll fix up this topic and the other JS interop topic, too. Thanks for calling this out.
