### ISSUE TITLE
When WithName is removed, route name is not automatically inferred

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/AspNetCore.Docs#26965]
According to the documentation as shown below,

![minimal](https://user-images.githubusercontent.com/50270635/189516212-7edc675f-4ddd-4ba0-b726-95ba0aa9d575.png)

route names will be inferred from the method name. 

Unfortunately the claim does not work.
If I remove `WithName(nameof(Hello))` then `Results.CreatedAtRoute(nameof(Hello), null, "Ok"))` throws an exception.

> System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Http.HttpResults.CreatedAtRoute`1.ExecuteAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteResultWriteResponse(IResult result, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

# Minimal Working Example

```csharp
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.OpenApi;

var builder = WebApplication.CreateBuilder(args);


builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();


if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

string Hello() => "Hello World";

// app.MapGet("/url", Hello); // Route name is not automatically inferred!
app.MapGet("/url", Hello).WithName(nameof(Hello));
app.MapGet("/", () => Results.CreatedAtRoute(nameof(Hello), null, "Ok"));


app.Run();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
Fixed by #27424
