### ISSUE TITLE
There is no fallback created in this document or the .NET 8 template for the Blazor Server example

### ISSUE THREAD

**Issue by affinity7software** [dotnet/AspNetCore.Docs#31216]
### Description

[Enter feedback here]
1) I don't understand how to set up a fallback for a new blazor server chat app. see links below. I'm getting multiple endpoints without creating a fallback.  There are lots of docs for fallbacks on older versions of .Net with examples and new examples that seem to create duplicate endpoints for me.

I'm trying to get this to work with dotnet 8.0 on a windows 11 pc to start.

[Use ASP.NET Core SignalR with Blazor | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio) 

I'm using the the second part of the doc "Blazor Server experience" 

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio#blazor-server-experience

I don't understand this part:

"Between the endpoints for mapping the Blazor hub and the client-side fallback, add an endpoint for the hub immediately after the line app.MapBlazorHub();:"

C#Copy

app.MapHub<ChatHub>("/chathub");

With this code in Programs.cs I get a runtime error:

app.MapBlazorHub();
app.MapHub<ChatHub>("/chathub");
app.Run();

Runtime error:

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Blazor web static files
Blazor web static files
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.TryServeStaticFile(HttpContext context, String contentType, PathString subPath)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
The thread 0x8bc4 has exited with code 0 (0x0).
The thread 0x5aa4 has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (0x277c) has exited with code 0 (0x0).
The thread '[Thread Destroyed]' (0x240c) has exited with code 0 (0x0).
The thread 0x4238 has exited with code 0 (0x0).
The thread 0x38d4 has exited with code 0 (0x0).
The thread 0x3260 has exited with code 0 (0x0).

 With this code I get a runtime error as well:

app.MapBlazorHub();
app.MapHub<ChatHub>("/chathub");
app.MapFallbackToPage("/");
app.Run();

same for app.MapFallbackToPage("/Home");

this produces a runtime error:

System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /, area:  }.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|10_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
The thread 0x1c8 has exited with code 0 (0x0).
The thread 0x2118 has exited with code 0 (0x0).
The thread 0x97e8 has exited with code 0 (0x0).
The thread 0x3d2c has exited with code 0 (0x0).

Thanks for your help!

Brian.
brian@affinity7software.com

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio#blazor-server-experience

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md

### Document ID

85af7a99-672c-0438-dcc2-e8edfaf70c54

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @affinity7software ... You're looking at the .NET 6 version of the doc. Change your doc version selector to .NET 8 to load the updated content.

There's also the updated sample app at ...

https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorSignalRApp

I'll close as answered, but I can re-open this issue if we need to chat further.

**Comment by affinity7software** [comment]
@guardrex , I didn't even see the selector, thanks! and thanks for the link  to the updated sample app!

**Comment by affinity7software** [comment]
> Hello @affinity7software ... You're looking at the .NET 6 version of the doc. Change your doc version selector to .NET 8 to load the updated content.
> 
> There's also the updated sample app at ...
> 
> https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorSignalRApp
> 
> I'll close as answered, but I can re-open this issue if we need to chat further.

Hi @guardrex, I followed this link to deploy that on nginx, https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-8.0&tabs=linux-ubuntu and I got errors on the HOME - chat page, I was able to see other pages ok, see secure websockets for the counter from my pc to the app behind an Nginx reverse proxy and AWS ALB passing HTTP request which got upgraded. I have not implemented the secure Nginx part described in the Microsoft link which I will try next but the chat part is failing on in:
BlazorSignalRApp.Components.Pages.Home.OnInitializedAsync() in Home.razor
51         await hubConnection.StartAsync();
 I'm happy to share a zip or just the Program.cs as it's the only thing I'm changing.

**Comment by guardrex** [comment]
The product unit provided guidance for Linux at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-8.0#linux-with-nginx

If that doesn't work (and the links mentioned there), open a new issue from the bottom of that article.
