### ISSUE TITLE
Example Does Not Work

### ISSUE THREAD

**Issue by thegreatco** [dotnet/AspNetCore.Docs#32528]
### Description

Running the code yields
```
Unhandled exception. System.InvalidOperationException: Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking. The underlying HTTP transport must be a SocketsHttpHandler with no SocketsHttpHandler.ConnectCallback configured. The HTTP transport must be configured on the channel using GrpcChannelOptions.HttpHandler.
   at Grpc.Net.Client.GrpcChannel.ValidateHttpHandlerSupportsConnectivity()
   at Grpc.Net.Client.GrpcChannel.ConnectAsync(CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /mnt/d/Dropbox/dev/GitHub/viam-dotnet-sdk/examples/ConsoleApp1/Program.cs:line 20
   at Program.<Main>(String[] args)
Aborted
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-uds?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/interprocess-uds.md

### Document ID

9af2ca8f-eefb-ae3d-ba52-d6b2a826945d

### Article author

@JamesNK

**Comment by JamesNK** [comment]
See https://github.com/grpc/grpc-dotnet/issues/2428

**Comment by wadepickett** [comment]
Thanks James! I'll add a note to the doc.  Thanks @thegreatco for letting us know your experience with the doc, greatly appreciated.
