### ISSUE TITLE
The -sqlite option is not recognized by the aspnet-codegenerator command

### ISSUE THREAD

**Issue by bonasunu** [dotnet/AspNetCore.Docs#34420]
### Description

**Description**

I try to run this command for Linux.

`dotnet aspnet-codegenerator razorpage -m Student -dc ContosoUniversity.Data.SchoolContext -udl -outDir Pages/Students --referenceScriptLibraries -sqlite`

I encountered an issue.

`dotnet aspnet-codegenerator razorpage -m Student -dc ContosoUniversity.Data.SchoolContext -udl -outDir Pages/Students --referenceScriptLibraries -sqlite
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Specify --help for a list of available options and commands.
Unrecognized option '-sqlite'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName, Boolean ignoreContinueAfterUnexpectedArg)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:17.49`

The issue is unrecognized option '-sqlite'.

I think this document should include `-dbProvider` for sqlite option.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-9.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md

### Document ID

fa488196-1f98-08ea-adcc-17d9dac86727

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+fa488196-1f98-08ea-adcc-17d9dac86727)

**Comment by drjeffjackson** [comment]
This is also an issue for Windows.  The #34421 fix is only for Linux.
