### ISSUE TITLE
RPmovieSQLiteNewField and RPmovieNewField has Migrations files broken

### ISSUE THREAD

**Issue by JulioJu** [dotnet/AspNetCore.Docs#9863]
Hi,

Actually, the project doesn't work, and especially if I let class RazorPagesMovie.Models.Movie as follow:
```csharp
        public int ID { get; set; }
```

But this work if we replace by 
```csharp
        public int Id { get; set; }
```

I'm on **Linux** and I've tested with SqlServer. In fact, the official example let this possibility https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieSQLiteNewField/Startup.cs . 

Maybe, it's normal, because as https://docs.microsoft.com/en-us/ef/core/modeling/keys said, the convention is « By convention, a property named ***Id*** or \<type name\>Id will be configured as the key of an entity. »

Maybe it works on Windows because this system is case insensitive, but maybe doesn't work on Linux because this system is case sensitive.

I havn't a Mac, but maybe this problem could occur on Mac as this system is Case sensitive.

Actually the output is :
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert
the value NULL into column 'ID', table 'RazorPageMovie.dbo.Movie'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues,
 CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, Cancellation
Token cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at RazorPagesMovie.Pages.Movies.CreateModel.OnPostAsync() in /tmp/RazorPagesMovie/RPmovieSQLiteNewField/Pages/Movies/Create.cshtml.cs:line 45
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

Thanks in advance for your answer !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JulioJu** [comment]
An other solution is to add [key] on the line above like this:
```cshtml
        [Key]
        public int ID { get; set; }
```

**Comment by Rick-Anderson** [comment]
@JulioJu 	let me know if you have any good tips on ASP.NET Core development on **Linux**

**Comment by JulioJu** [comment]
@Rick-Anderson I could make the PR if you want ;-).

**Comment by Rick-Anderson** [comment]
@JulioJu 	thanks for the offer, but it's more complicated with all the code and the docs. We'll get this fixed when we do the 3.0 version.

Thanks again for the offer.

**Comment by JulioJu** [comment]
@Rick-Anderson 

I've tested again, and our analyses was completely false. Sorry. 

I've tested again because as I'm new on `dotnet` I like to use your `out-of-box` samples to understand well some concepts. And I've discovered that uppercase ID work fine for Contoso sample. Therefore I've investigate further. 

<hr />

For: 
* RPmovieSQLiteNewField https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieSQLiteNewField 
* RPMovieNewField https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieNewField
* On Linux Problem, the problem is not that ID is in uppercase, the problem is with Migrations files. In don't know what this migrations files bugs on Linux, but it's not due of uppercase ID. 
* Solve perfectly the problem by simply generate completely new Migrations with command : 

```sh
# See also https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.2&tabs=visual-studio-code 
dotnet ef database drop \
  &&  rm -Rf Migrations bin obj \
  && dotnet ef migrations add InitialCreate \
  && dotnet ef database update \
  && dotnet ef migrations add Rating \
  && dotnet ef database update \
  && dotnet watch run
```

<hr />

* Contoso Example https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro/samples/cu/Models/Student.cs or 
* RPMovie Part3 https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovePart3  
* RPMovieSearch https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieSearch
* ==> all work fine with ID in uppercase. 

<hr />

Furthermore I've tested the following command without success for [RPMovieNewField](https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieNewField).

Following demonstrate that current Migration are completely broken on Linux Platform even if we replace all uppercase `ID` to `Id`.

```sh
find -name "*.cs*" -exec grep --color="always" ID {} + # to check what will be changed.
dotnet ef database drop \                                                                                                                                                              
  && find -name "*.cs*" -exec sed -i 's/ID/Id/g' {} + \
  && dotnet ef database update
```

<hr />
Sorry for the misinterpretation 

If you are ok I could make a PR to generate completely new Migrations files thanks command above for : 
* RPmovieSQLiteNewField https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieSQLiteNewField 
* RPMovieNewField https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovieNewField

I've generated thanks tools `dotnet-ef 2.2.1` (the last one today) and `dotnet-core 2.2.102`

**Comment by JulioJu** [comment]
If your are ok, 

* I could also add README for https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples 
* And I could correct README.md under folder https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples (cuFinal) does not exists)
* And correct error that appears caused of https://stackoverflow.com/questions/50825242/the-type-or-namespace-name-hosting-does-not-exist-in-the-namespace-microsoft

Furthermore there is a but with current

**Comment by wadepickett** [comment]
@Rick-Anderson, for this issue, if I understand it correctly, we can't use "ID" even if we are consistent about it because by the time it gets through migrations and data generation it is treated somewhere as "Id" instead?  Is this an issue to also raise for the product migration code?

If I understand what the fix is for the RP series, it is to redo all versions and the sub-variations of app samples (there are a lot in this series) with Id instead of ID, plus of course where it is mentioned in the tutorials?  

Just thought I would verify in case the fix is simpler and more isolated than I am understanding it to be.  I didn't want to needlessly redo all the previous versions of the app and sub-variations,  sdk versions, IDE versions and sub-variations (sqlserver and sqlLite), unless that really is the only avenue.   Many thanks for your insight.

**Comment by Rick-Anderson** [comment]
I'd put this on hold as we've only had one person report the problem.

**Comment by wadepickett** [comment]
@Rick-Anderson,  thanks, I was already feeling like I was overloading the RP 5.0 update as it was with the backlog into a rather large and complicated PR with perhaps too many issues at once.  This one really needs its own dedicated PR if it moves up in the priority list.  It certainly is a n interesting issue though.
